### PR TITLE
support for @property on classes (including tests)

### PR DESCRIPTION
**Pull request by aidinabedi**
We need support for class properties and since #73 has not been updated since May. I decided to take it upon myself to fulfill the requirement regarding tests, as stated in https://github.com/englercj/tsd-jsdoc/pull/73#issuecomment-493285402.

So this PR is based on the work done by @HackbrettXXX, with the addition of test cases. See output: https://travis-ci.org/englercj/tsd-jsdoc/builds/575963771#L251

### CODE REVIEW

**Comment by englercj** [comment]
Thanks @aidinabedi for adding tests. Glad you did, because it looks like `PropTest3` and `PropTest6` are not valid Typescript.

They both contain:

```
{
    myProp: boolean;
    myProp: boolean;
}
```

**Comment by aidinabedi** [comment]
It's not the job of `tsd-jsdoc` to output valid TypeScript in that test. The output is intentionally meant to be duplicate properties because I wrote "invalid" jsdoc comments, i.e. describing the same property twice. Which I could just as well do using other jsdoc tags (without the PR). I wanted to have a test to make sure the behavior is still the same, and `tsd-jsdoc` isn't trying to be smart in this "special" case. To quote the readme:
```
This library provides very little validation beyond what JSDoc provides. Meaning if you have invalid JSDoc comments, this will likely output an invalid TypeScript Definition File.
```

**Comment by aidinabedi** [comment]
@englercj I've added additional duplicates to illustrate that the behavior is the same, whether you use `@property` or regular `@type` tags.

**Comment by englercj** [comment]
Fair enough.

**Comment by HackbrettXXX** [comment]
Thanks for providing the tests @aidinabedi. Couldn't find the time myself.

**Comment by aidinabedi** [comment]
@HackbrettXXX No problem!

**Pull request merged**
