### PR TITLE
Check if members of class/interface are valid and iterable

### LINKED ISSUE #44: TypeError: o.members is not iterable
```
$ npm ls | grep jsdoc
+-- jsdoc@3.5.5
`-- tsd-jsdoc@2.0.0-beta.5
```

First up: its a bit annoying that you changed the required template path from `./node_modules/tsd-jsdoc` to `./node_modules/tsd-jsdoc/dist` after `2.0.0-beta.3` without mentioning it anywhere.

But my main issue is the following:
```
$ jsdoc -c config.json
sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:183
                for (const member of o.members) {
                                       ^

TypeError: o.members is not iterable
    at Emitter._resolveObjects (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:183:40)
    at Emitter.parse (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:39:14)
    at new Emitter (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\Emitter.js:30:14)
    at Object.publish (sinusbot-scripting-docs\node_modules\tsd-jsdoc\dist\publish.js:11:21)
    at Object.module.exports.cli.generateDocs
...
```
This can be reproduced by cloning [SinusBot/scripting-docs](https://github.com/SinusBot/scripting-docs), installing `tsd-jsdoc@2.0.0-beta.5` and running the command provided above.

Almost forgot: you also have to change the `template` path in the `config.json` as mentioned at the beginning...

### PR DESCRIPTION
**Pull request by bampakoa**
@englercj very nice library. Congrats for this effort!

Fixes #44

### CODE REVIEW

**Comment by englercj** [comment]
Hey @bampakoa thanks for the PR.

This fixes the symptom, but what is the cause? Why is `.members` non-iterable?

**Comment by bampakoa** [comment]
I am using your library while trying to create types for [CesiumJS](https://cesiumjs.org/) and I hit on the same error as #44 . I have not dig deeper as what caused this issue, that is which jsdoc statement is responsible for the error, but I believe that the library should not be terminated unexpectedly in such a case. I could investigate though for the sake of this PR :smiley:

**Comment by englercj** [comment]
I agree it shouldn't terminate, but if that value is empty it likely points to a bug somewhere. I have a feeling that something else is wrong which causes it to be empty rather than it being empty is legit and we should catch it.

Merging this as-is may hide an actual bug is what I'm driving at. If it turns out that it can be empty sometimes because that's just how JSDoc is, then that is totally fine and I'll merge this. Otherwise, we should fix whatever the underlying issue is.

**Comment by bampakoa** [comment]
@englercj sure. I will run the debugger to see what is actually going on and I will get back to you.

**Comment by bampakoa** [comment]
@englercj my error was caused by wrong configuration of `jsdoc` block comments There was nothing to do with `tsd-jsdoc`. I think that at the end of the day, it would be nice to have this fix.

**Comment by englercj** [comment]
I had a suspicion that was the case. Can we add an else here that logs that something is wrong and give as much information as possible so users can track down the misconfigurations like you encountered?

**Comment by englercj** [comment]
Wonderful, thanks!

**Pull request merged**
